[theme]
primaryColor="#E63946"  # A vibrant coral red
backgroundColor="#1B1B2F"  # Deep midnight blue
secondaryBackgroundColor="#16213E"  # Dark blue with a hint of purple
textColor="#A5C9CA"  # Soft cyan for a pleasing contrast with dark backgrounds
font="monospace"  # Monospace for a tech-savvy look
